theme: jekyll-theme-cayman
title: Homemade code
description: If it is not keeping you up at night, then it is not a real problem
google_analytics: G-3WFG78WYL1
excerpt_separator: <!--more-->
paginate: 5
paginate_path: "/blog/page:num/"
